### ISSUE TITLE
Handle user pressing back button during test

### ISSUE THREAD

**Issue by sugrinov** [execom-eu/OOP-Test-Generator#187]
If user presses back button during test and fills in the form check if he selected the same test category.
Handle next cases:
  - User selected same category => give him the same test
  - User selected another category => generate a new test

**Comment by millevlada** [comment]
Currently, if user navigates back and again clicks 'I want to be an Execom employee' he restarts that same test with the time remaining from last activity. If this functionality needs to be changed to what was originally described, please revisit this issue. However, it is noticed that revisiting the test this way would cause timer ticks to fire multliple times - causing time to countdown faster -> at least that should be fixed.

**Comment by dujfalusi** [comment]
From the backend perspective, everything works fine, remaining time updates on answer update or finishing the test. Getting the test client receives remaining time for a given test. If a test didn't updated with an answer, the test wouldn't be updated for remaining time. 

On the front side, these problems still occur. 
1. Going back with the `Back` button isn't possible anymore but that screen still doing fetch `getTestById`. 2. Multiple clicking on the `Back` button causing the time to countdown faster.
3. When the time comes under 3 min breaks with error
![image](https://user-images.githubusercontent.com/19993915/59419888-267bc080-8dcc-11e9-9357-338d4a4a719f.png)

What I could propose instead fetch getTest by id on the `Back` button to update the test, that if someone clicks on the back button will update the remaining time.

**Comment by Fistulator** [comment]
It seems like every press of the back button makes a new instance of the countdown component, so the time that remains for a test is drastically shortened.

**Comment by Fistulator** [comment]
Fixed in pull request #391.
